#!/bin/sh /etc/rc.common
# freemesh startup script

START=99 
STOP=99 

start() {
    echo "`date` - starting /etc/init.d/fmstartup" >> /tmp/fmlog;

	#Turn the green status light on so we can see it started
	echo "none" > /sys/class/leds/blue:status/trigger;
	echo "none" > /sys/class/leds/green:status/trigger;

	echo "1" > /sys/class/leds/blue:status/brightness;
	echo "1" > /sys/class/leds/green:status/brightness;

	if [ "$(uci get fm.router.firstboot)" == 1 ]; then
		/freemesh/firstboot.sh
	fi

	echo "`date` - ending /etc/init.d/fmstartup" >> /tmp/fmlog;
}

stop() {
        # nothing is actually running, so do nothing
	return
}

