#!/bin/sh /etc/rc.common
# freemesh startup script

START=99
STOP=99

start() {
    echo "`date` - starting /etc/init.d/fmstartup" >> /tmp/fm.log
    sleep 15
    /freemesh/node_startup.sh
    echo "`date` - ending /etc/init.d/fmstartup" >> /tmp/fm.log
}

stop() {
    true
    # commands to kill the application
}